# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  flutter_application_path = '../my_flutter/'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios_flutter_url_route' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_flutter_url_route
  install_all_flutter_pods(flutter_application_path)

  target 'ios_flutter_url_routeTests' do
    inherit! :search_paths
    # Pods for testing
    install_all_flutter_pods(flutter_application_path)
  end

  target 'ios_flutter_url_routeUITests' do
    # Pods for testing
  end

end
